---

- name: git clone redis-leveldb
  git:
    repo=https://github.com/KDr2/redis-leveldb.git
    dest={{ toolsetdir }}/redis-leveldb

- name: redis-leveldb dependencies
  package: name={{item}} state=present
  with_items: "{{ redis_leveldb_deps }}"

- name: compile redis-leveldb
  command: "{{ item }} chdir={{ toolsetdir }}/redis-leveldb creates={{ toolsetdir }}/redis-leveldb/redis-leveldb"
  with_items:
    - make
#    - make test

- name: install redis-leveldb
  copy: src={{ toolsetdir }}/redis-leveldb/redis-leveldb dest=/usr/local/bin/redis-leveldb mode=0755 remote_src=yes

